name: Static security tests
on: [push]
jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: sudo apt-get install flake8
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: Run flake8
        run: flake8
  bandit:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get -qq update && sudo apt-get -qq -y install bandit
      - uses: actions/checkout@v2
      - run: bandit -r .

